### ISSUE TITLE
submodule awareness

### ISSUE THREAD

**Issue by alrunner4** [ehamiter/GitHubinator#23]
I really enjoy jumping directly to github blame from Sublime, but it's extra work when I want to jump into a submodule (I have to manually edit the url to point to the submodule repo rather than the main repo). It would be super convenient if GitHubinator could notice that the current file is in a submodule and react accordingly.

**Comment by avaly** [comment]
+1

**Comment by neerolyte** [comment]
+1

**Comment by lachenmayer** [comment]
+1 - would make my life so much easier!

**Comment by bastianl** [comment]
+1, I have been noticing this as well

**Comment by aukehuizinga** [comment]
+1

Maybe this can be of inspiration:
I made a function that opens the github pull request webpage on Ubuntu by typing `pr` on the command line:
```
pr() {
	REMOTE=`git ls-remote --get-url | cut -f2 -d":"| cut -f1 -d"."`
	BRANCH=`git rev-parse --abbrev-ref HEAD`
	xdg-open "http://github.com/$REMOTE/compare/$BRANCH?expand=1"
}
```
I placed this in my `~/.zshrc` file (I'm using oh-my-zsh as shell). 

Based on that function I also made a `git-open` command which does kinda the same as githubinator, but is limited to the terminal:
```
TYPE=blob
BRANCH=`git rev-parse --abbrev-ref HEAD`
FILE=`git rev-parse --show-prefix`

# Parse input
while test $# -gt 0; do
        case "$1" in
		-b|--blame)
			TYPE="blame"
			shift
			;;
		-h|--history)
			TYPE="commits"
			shift
			;;
		-m|--master)
			BRANCH="master"
			shift
			;;
		*)
			FILE=$FILE"$1"
			shift
			;;
	esac
done

REMOTE=`git ls-remote --get-url | cut -f2 -d":"| cut -f1 -d"."`
xdg-open "http://github.com/$REMOTE/$TYPE/$BRANCH/$FILE"
```
This is placed in `/usr/sbin/git-open`.

Using this commands I never found any issues with open submodule stuff, so maybe they can be building blocks to base the change for this issue on.

**Comment by deadlyicon** [comment]
please add submodule support!

**Comment by gka** [comment]
here's a PR that adds submodule support https://github.com/ehamiter/GitHubinator/pull/71

**Comment by ehamiter** [comment]
@gka contributed some code that should resolve this issue.
