### ISSUE TITLE
fix for commits

### ISSUE THREAD

**Issue by afeld** [ehamiter/GitHubinator#24]
when you are checked out to a commit (vs. a branch), all of the Githubinator menu commands result in an error like this:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./githubinator.py", line 61, in run
IOError: [Errno 2] No such file or directory: u'/path/to/my/project/.git/ff88f0b246dc6606d520c7f46a546457ea55bdf8'
```

i'm sure it's a simple change, just haven't gotten around to fixing

**Comment by chdsbd** [comment]
This is a dupe of #66 and was fixed in #68
