### ISSUE TITLE
Github now requires #L100-L200 anchor for line numbers ranges

### ISSUE THREAD

**Issue by kevinastone** [ehamiter/GitHubinator#38]
Otherwise it only highlights the first line number.

Example:
https://github.com/twbs/bootstrap/blob/master/less/buttons.less#L133-L143

This will only link the first line:
https://github.com/twbs/bootstrap/blob/master/less/buttons.less#L133-143

**Comment by dcook-squiz** [comment]
Turns out GitLab still uses the other format (`#Lnnn-mmm`), so this is now broken for GitLab :(
