### ISSUE TITLE
Very strange URL from GitHubinator

### ISSUE THREAD

**Issue by toldani** [ehamiter/GitHubinator#44]
First off, this is our .git/config file:

> [core]
>    repositoryformatversion = 0
>    filemode = true
>    bare = false
>    logallrefupdates = true
>    ignorecase = true
>    precomposeunicode = false
> [remote "origin"]
>    url = ssh://git@github.com/fakeuser/fakeproject.git
>    fetch = +refs/heads/*:refs/remotes/origin/*
> [branch "json_turn"]
>    remote = origin
>    merge = refs/heads/json_turn
> [branch "ed5"]
>    remote = origin
>    merge = refs/heads/ed5`

It's being parsed wrong somehow, because URLs end up coming out looking like this, when you copy them to the clipboard:

`https://github.com/fakeuser/fakeproject.git fetch = +refs/heads/*/refs/remotes/origin/*/blob/ed5/lib/ed.rb#L176-L184`

Real URL should be something like:

`https://github.com/fakeuser/fakeproject/blame/ed5/lib/ed.rb#L176-L184`

Only the "user" and "project" were replaced with fake values, the rest are real.  "ed5" is our current branch, for example.  Anything not in square brackets in our .git/config file is indented with a tab.

**Comment by karlhorky** [comment]
I also had this error.

I fixed this by changing the remote origin to the URL that GitHub displays for cloning from SSH:

```diff
[remote "origin"]
- url = ssh://git@github.com/fakeuser/fakeproject.git
+ url = git@github.com:fakeuser/fakeproject.git
```

Should be documented somewhere? Or maybe it should be fixed in the Sublime Package?
