### ISSUE TITLE
urllib.parse causes error

### ISSUE THREAD

**Issue by jbandhauer** [ehamiter/GitHubinator#48]
FYI, The change in https://github.com/ehamiter/GitHubinator/pull/47 broke the package for me. I now get:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./githubinator.py", line 73, in run
AttributeError: 'module' object has no attribute 'parse'
```

I stuck in a 'print urllib' line to see what it might say. I get:
`<module 'urllib' from '/usr/lib/python2.6/urllib.py'>`

I'm using sublime text 2 on OS X Yosemite.

My python is pretty rusty. I'm not sure if this is simply a python version incompatibility or what. Is there a more generic way to do what the PR is doing? 

Thanks!

**Comment by ehamiter** [comment]
Confirmed-- urllib is different for Python 2/3. Just pushed up a code change that should fix it, so uninstall and reinstall GitHubinator and it should be working for you.

**Comment by jbandhauer** [comment]
That works for me. Thanks so much! 
BTW, I really appreciate this package.
