### ISSUE TITLE
Remove username from url to prevent annoying popup

### ISSUE THREAD

**Issue by cmalard** [ehamiter/GitHubinator#56]
When a username is present in a repo url (https://username@github.com/org/repo.git) to simplify [https auth](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended) (no need to provide user), the browser displays an annoying pop-up: 
>You are about to log on to the site "github.com" with the username "username", but this website does not require authentication. This may be an attempt to mislead you. Is "Github.com" the site you want to visit?

We should remove `username@` from the url before opening the page.

From: https://cmalard@github.com/ehamiter/GitHubinator/blob/master/githubinator.py#L115
to: https://github.com/ehamiter/GitHubinator/blob/master/githubinator.py#L115

**Comment by cmalard** [comment]
@ehamiter as I understant, the PR does not close this issue at all ?

**Comment by ehamiter** [comment]
It does not, and I didn't mean to close it-- I just merged a related item and I guess since it was linked in this PR, it closed it as resolved.
