### ISSUE TITLE
Support custom default branch

### ISSUE THREAD

**Issue by jamesarosen** [ehamiter/GitHubinator#73]
For commands like _Open on master_ and _Open blame on Master_, it would be nice to support a default branch other than `master`. Lots of repos are switching over to `main` because of the negative implications of "master".

See https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

Related: #63

**Comment by Minkey27** [comment]
This is possible by editing Default.sublime-commands. 

Copy paste one of the commands properly and alter the caption and the branch.

From:
```
  {
    "caption": "GitHubinator Blame on Master",
    "command": "githubinator",
    "args": { "permalink": false, "mode": "blame", "branch": "master" }
  },
```
To:
```
  {
    "caption": "GitHubinator Blame on Main",
    "command": "githubinator",
    "args": { "permalink": false, "mode": "blame", "branch": "main" }
  },
```

**Comment by ehamiter** [comment]
Thanks for commenting @Minkey27 -- I'll add this to the README.

**Comment by ehamiter** [comment]
Added.
